from __future__ import annotations


DEFAULT_MISSING_POLICY = "drop"
DEFAULT_TARGET_INCLUSION_RATE = 0.70
DEFAULT_SELECTION_STRENGTH = 1.0
DEFAULT_SEED = 42

DEFAULT_KEEP_SELECTION_COLUMNS = True
DEFAULT_SAVE_ANNOTATED_DATASET = True
DEFAULT_VALIDATE_TREATMENT_AS_BINARY = True
DEFAULT_INCLUDE_TREATMENT_IN_SELECTION = False
DEFAULT_TREATMENT_WEIGHT = 0.0

DEFAULT_SCALED_SUFFIX = "_scaled"

DEFAULT_LINEAR_SCORE_COLUMN = "selection_linear_score"
DEFAULT_PROBABILITY_COLUMN = "selection_probability"
DEFAULT_INDICATOR_COLUMN = "selection_indicator"

SUPPORTED_MISSING_POLICIES = {"drop", "mean-impute"}
SUPPORTED_INPUT_SUFFIXES = {".csv", ".parquet"}
SUPPORTED_OUTPUT_SUFFIXES = {".csv", ".parquet"}
SUPPORTED_REPORT_SUFFIXES = {".json"}