import json
import re
import logging
from typing import Dict

logger = logging.getLogger(__name__)


class StrictJSONParser:
    """
    A deterministic and fault-tolerant parser for extracting structured data.
    Instead of validating the entire JSON array, it extracts individual {...} blocks,
    attempts to repair common LLM syntax errors, and recovers valid data.
    """

    def _repair_and_parse_block(self, block: str) -> dict:
        """
        Applies regex-based heuristics to repair common syntax errors
        generated by LLMs before attempting JSON parsing.
        """
        # 1. Basic substitutions (e.g., angle brackets instead of braces)
        fixed = block.replace('<', '{').replace('>', '}')

        # 2. Case: { 3, 0.08 } -> Completely missing keys and colons
        fixed = re.sub(r'\{\s*(\d+)\s*,\s*([-\d\.]+)\s*\}', r'{"id": \1, "cate": \2}', fixed)

        # 3. Case: keys without quotes e.g. {id: 3} -> {"id": 3}
        fixed = re.sub(r'([{,]\s*)([a-zA-Z_]+)(\s*:)', r'\1"\2"\3', fixed)

        # 4. Case: {"id": 3, 0.08} -> CATE value without key (your specific error)
        fixed = re.sub(r'("id"\s*:\s*\d+\s*,\s*)([-\d\.]+)(\s*\})', r'\1"cate": \2\3', fixed)

        # 5. Case: {"": 3, "cate": 0.08} -> Empty ID key
        fixed = re.sub(r'\{\s*""\s*:\s*(\d+)', r'{"id": \1', fixed)

        # 6. Case: {"id": 3, "": 0.08} -> Empty CATE key
        fixed = re.sub(r',\s*""\s*:\s*([-\d\.]+)', r', "cate": \1', fixed)

        # Try converting the repaired string into a dictionary
        return json.loads(fixed)

    def parse(self, text: str) -> Dict[int, float]:
        """
        Extracts and maps IDs to CATE values, isolating individual tuples
        to prevent a single error from breaking the entire batch.
        """
        if not text:
            raise ValueError("Empty LLM output")

        # Instead of looking for [ and ], extract ALL blocks that look like dictionaries {...}
        # This automatically ignores any preceding or trailing text.
        blocks = re.findall(r'\{[^}]+\}', text)

        if not blocks:
            raise ValueError("No JSON objects found in text")

        result = {}

        for block in blocks:
            try:
                # Attempt to repair and parse the single element
                item = self._repair_and_parse_block(block)

                if not isinstance(item, dict):
                    logger.warning(f"Element must be an object, got: {type(item)}")
                    continue

                if set(item.keys()) != {"id", "cate"}:
                    logger.warning(f"Invalid fields in item: {item}")
                    continue

                raw_id = item["id"]
                raw_cate = item["cate"]

                # Type constraint: identifier must be integer
                if isinstance(raw_id, bool) or not isinstance(raw_id, int):
                    logger.warning(f"ID must be int: {raw_id} (type: {type(raw_id)})")
                    continue

                # Type constraint: value must be numeric (int or float)
                if isinstance(raw_cate, bool) or not isinstance(raw_cate, (int, float)):
                    logger.warning(f"CATE must be numeric: {raw_cate} (type: {type(raw_cate)})")
                    continue

                _id = int(raw_id)
                cate = float(raw_cate)


                # Enforce uniqueness of identifiers
                if _id in result:
                    logger.warning(f"Duplicate ID detected: {_id}")
                    continue


                # Ensure uniqueness
                if _id not in result:
                    result[_id] = cate

            except (json.JSONDecodeError, ValueError, KeyError) as e:
                # Log the failure of the SINGLE element, but do not interrupt the loop
                logger.debug(f"Unable to parse or validate block '{block}': {e}")
                continue

                # If nothing was extracted after the loop, it's a total failure
        if not result:
            raise ValueError("No valid items extracted after repair attempts")

        return result





